name: html2data
version: '1.2.1'
summary: extract data from HTML via CSS selectors
description: Command line utility for extracting data from HTML via CSS selectors.
grade: stable
confinement: strict
base: core18
parts:
  html2data:
    plugin: go
    go-importpath: github.com/msoap/html2data
    source: .
    source-type: git

apps:
  html2data:
    command: bin/html2data
    plugs: [network, home]
